#!/usr/bin/env python3
# -*- coding:utf-8 -*-

with open("input_example1", "r+", encoding="utf-8") as input_f:
    input_list = input_f.readlines()


def parse(list_to_parse) -> tuple[str, dict[str, tuple[str, str]]]:
    """Return a str and a dict of str: (str, str)"""
    directions = ""
    nodes = dict()
    for i, line in enumerate(list_to_parse):
        if line == "\n":
            continue
        if i == 0:
            directions = line[:-1]
            continue
        line = line[:-1].split()
        nodes[line[0]] = (line[2][1:-1], line[3][:-1])
    return directions, nodes


print(parse(input_list))

